name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Ejecutar Sonar Scanner
        run: |
          .\sonar-scanner.bat -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
        shell: cmd

